spring:
  application:
    name: booking-service
  datasource:
    url: mysql://localhost:3306/Ride_Review_DB_Local
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
server:
  port: 7478
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

#spring.datasource.url=jdbc:mysql://localhost:3306/Ride_Review_DB_Local
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=validate
#server.port=7478
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

#eureka.client.serviceurl.defaultzone: http://localhost:8761/eureka
#eureka.client.instance.preferIpAddress: true
